### ISSUE TITLE
Правила хорошего тона - requirements.txt

### ISSUE THREAD

**Issue by Rus-Iva** [yeezy-na-izi/YlDjango#1]
Сейчас задание было простым, с указанием фрейморка и его версии, но в жизни все, конечно же не так просто.
Поэтому существует [такая замечательная вещь](https://pip.pypa.io/en/1.1/requirements.html#freezing-requirements)
Сделано это для того, чтобы разработчик, пользующийся твоим проектом, не ломал голову с ручной установкой библиотек и проверкой совместимости версий.
Это нужно добавлять в репозиторий.

**Comment by yeezy-na-izi** [comment]
Добавил
