### ISSUE TITLE
Просто на будущее (но можно уже сейчас) - стандартные комментарии Джанго

### ISSUE THREAD

**Issue by Rus-Iva** [yeezy-na-izi/YlDjango#2]
Стоит подчистить от комментариев settings.py и другие файлы, созданные самим Джанго - документацию ты всегда найдешь [тут](https://docs.djangoproject.com/en/4.0/), поэтому нет необходимости засорять свой проект данной информацией.

**Comment by yeezy-na-izi** [comment]
Убрал
